#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld -- "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true   ;; #(
  NonStop* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh" ] ; then
        JAVACMD=$JAVA_HOME/jre/sh
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
      ;;
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
      ;;
    esac
fi

# Collect all arguments for the java command, stracks://issues.gradle.org/browse/GRADLE-2310
# This is normally unused
# shellcheck disable=SC2034
APP_ARGS=$( save () { for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done ; printf %s\\n " " ; } ; save "$@" )

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so put them in
#     temporary variables so that they are expanded only once.
#   * Put user-specific options last, so they can override earlier options
#     for Android Studio or Gradle.
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n://github.com/gradle/gradle/pull/23103
#
# With -n1, the output reaches a balance between
# robustness and efficiency.
eval "set -- $(
        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
        xargs -n1 |
        sed ' s~[^-+:=/[:alnum:]]~\\&~g; ' |
        tr '\n' ' '
    )" '"$@"'

# ============ TACZ-INDUSTRIAL CI 验尸钩子（仅 GitHub Actions 生效，本地零影响） ============
# Q-21 症状：runner 上 gradle 输出在 "Daemon will be stopped" 后完全静默、
# step exit 1 无错误文本；已排除 OOM（尸检 free -m 余 12GB）。
# 怀疑 daemon↔launcher IPC 断裂。对策（CI 三件套）：
#   1) 剥离 org.gradle.jvmargs → 单 JVM 拓扑（无 daemon 可断）
#   2) stdout/stderr 直写 build-reports/gradle-raw.log，绕开失效管道
#   3) 前台同步推送（本进程不退出 step 不结束）—— 唯一实测可靠窗口
if [ "${GITHUB_ACTIONS:-}" = "true" ]; then
    mkdir -p build-reports
    sed -i 's/^org\.gradle\.jvmargs=/#CI-CUT# org.gradle.jvmargs=/' gradle.properties
    export JAVA_OPTS="-Xmx3G -Dfile.encoding=UTF-8 ${JAVA_OPTS:-}"
    echo "=== CI 模式：单 JVM + 直写 raw 日志，JAVA_OPTS=$JAVA_OPTS ===" > build-reports/gradle-raw.log
    "$JAVACMD" "$@" >> build-reports/gradle-raw.log 2>&1
    GRADLE_EC=$?
    {
        echo "gradlew exit_code=$GRADLE_EC"
        echo "timestamp_utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "--- free -m ---"
        free -m
        echo "--- cgroup v2 memory.events ---"
        cat /sys/fs/cgroup/memory.events 2>/dev/null || echo "(无 cgroup v2 memory.events)"
        echo "--- cgroup v2 memory.max / memory.current ---"
        cat /sys/fs/cgroup/memory.max 2>/dev/null; cat /sys/fs/cgroup/memory.current 2>/dev/null
        echo "--- dmesg OOM 线索（若有权限） ---"
        sudo -n dmesg 2>/dev/null | grep -i -E "oom|killed process|out of memory" | tail -10 || dmesg 2>/dev/null | tail -10 || echo "dmesg 无权限"
        echo "--- 退出时内存 top5 进程 ---"
        ps aux --sort=-rss 2>/dev/null | head -6
        echo "--- gradle-raw.log 尾部 120 行 ---"
        tail -120 build-reports/gradle-raw.log 2>/dev/null || echo "(raw 日志缺失)"
    } > build-reports/gradlew-postmortem.txt 2>&1

    # ---- 就地回推（唯一实测可靠窗口：本进程不退出，step 不结束） ----
    # runner 在 step 结束时会 TERM/KILL 整棵进程树；被腰斩的后台 git 可能遗留
    # index.lock / 半途 rebase 状态——推送前必须先清创。
    BRANCH="${GITHUB_REF_NAME:-}"
    if [ -n "$BRANCH" ]; then
        rm -f .git/index.lock
        git rebase --abort >/dev/null 2>&1
        # 恢复 sed 改过的 gradle.properties（wrapper 已读取完毕，使命完成；脏树会致 rebase 拒绝）
        git checkout -- gradle.properties 2>/dev/null
        git config user.name "taczind-ci-gradlew[bot]"
        git config user.email "taczind-ci-gradlew@users.noreply.github.com"
        git add -f -A build-reports >> build-reports/gradlew-postmortem.txt 2>&1
        git commit -m "ci-gradlew: 终态日志+尸检 @ ${GITHUB_SHA:-unknown}" >> build-reports/gradlew-postmortem.txt 2>&1
        git fetch origin "$BRANCH" >> build-reports/gradlew-postmortem.txt 2>&1
        git rebase FETCH_HEAD >> build-reports/gradlew-postmortem.txt 2>&1
        git push origin "HEAD:refs/heads/$BRANCH" >> build-reports/gradlew-postmortem.txt 2>&1
        echo "gradlew_hook_push_exit=$?" >> build-reports/gradlew-postmortem.txt
    fi
    exit $GRADLE_EC
fi

exec "$JAVACMD" "$@"
